version: "3"
services: 
  compiler:
    build:
      context: .
    command: /sbin/init
    container_name: compiler
    environment:
      - GOPATH=/go/src
      - XDG_RUNTIME_DIR=/run/user/0
    privileged: true
    tty: true
    volumes:
      - ./:/go/src/compiler